### ISSUE TITLE
Graphbio1-GOplot or Chord plot-Please Help! 

### ISSUE THREAD

**Issue by vipulbatra1985** [databio2022/GraphBio#1]
PFA the .csv and .xls files that are not producing any results in GOplot or Chord plot (An error has occurred. Check your logs or contact the app author for clarification. Please help. 
[SALT CHORD_GO_FINAL.csv](https://github.com/databio2022/GraphBio/files/9679152/SALT.CHORD_GO_FINAL.csv)
[SALT gochord.xlsx](https://github.com/databio2022/GraphBio/files/9679153/SALT.gochord.xlsx)
[SALTFINAL.xls](https://github.com/databio2022/GraphBio/files/9679154/SALTFINAL.xls)

**Comment by databio2022** [comment]
Thank you for using GraphBio. I have checked your file, and you should remove genes with 0 in all biological processes for your csv file.

**Comment by vipulbatra1985** [comment]
Do you mean all the 0 values from the dataset? The example file
says,  value 0 or 1 represents the relationship of gene and GO term. How
come?
Vipul

**Comment by vipulbatra1985** [comment]
What do I replace the zeros with?
Vipul

**Comment by vipulbatra1985** [comment]
![image](https://user-images.githubusercontent.com/47975001/193174029-8397e966-7b25-4f43-b56c-d442e559654d.png)

**Comment by vipulbatra1985** [comment]
I figured that out, thanks. However, I cant download figure in any of the listed formats.

**Comment by databio2022** [comment]
![image](https://user-images.githubusercontent.com/101156176/193175805-c61ab158-3b35-4b1b-a1e5-ca7a02e39868.png)
such as these lines, delete them. These genes are 0 for all pathways or biological processes, and they caused the error. Usually, a gene should have at least one value as 1 instead of all are 0.

**Comment by databio2022** [comment]
I tested, download function works well.

**Comment by vipulbatra1985** [comment]
There is still something wrong. Please see this file.
Vipul

**Comment by databio2022** [comment]
Hi,
Yes, log2FC column is not required. I checked your file and found your file contain 11 pathways or biological processes which over 8 colors allowed by default color1 parameter.  In this case, you can change color setttings as "color2" ("Select Colors" in right parameter settings panel) after upload file irresective of error information, it will work. This is result for your data. 
![image](https://user-images.githubusercontent.com/101156176/193370550-01d20a26-f8a0-4dca-8aa3-c7c9b22228c6.png)
