### ISSUE TITLE
heatmap error

### ISSUE THREAD

**Issue by Elseedy28** [databio2022/GraphBio#10]
[heatmap female.txt](https://github.com/databio2022/GraphBio/files/10991069/heatmap.female.txt)
Hello 
[metadata female.txt](https://github.com/databio2022/GraphBio/files/10991072/metadata.female.txt)
i am trying to draw heatmap but i ma usually having error i attached to you the files i am using 

best
heba

**Comment by databio2022** [comment]
Hi, I checked your file **heatmap female.txt** and found it is too large to work, so please reduce gene numbers and try again.
