### ISSUE TITLE
Chord Plot

### ISSUE THREAD

**Issue by vipulbatra1985** [databio2022/GraphBio#3]
I am not able to run the .csv for plotting the GO/Chord plots. Apparently, it looks fine. Please help!

**Comment by vipulbatra1985** [comment]
protection	immunomodulation	survival	maturation	zp-binding	capacitation	acrosome reaction	gamete intercation	maturation	spermatogenesis 	male fertility
A1BG	1	1	0	0	0	0	0	0	0	0	0
ABO	0	0	0	0	0	0	0	0	0	0	1
ACACB	0	0	0	0	0	0	0	0	0	0	0
ACHE	0	0	0	1	0	0	0	0	0	0	0
ACR	0	0	0	0	1	0	0	0	0	0	0
ACRBP	0	0	0	0	1	0	0	0	1	0	0
ACRV1	0	0	0	0	1	0	0	0	0	0	0
ACTL7A	0	0	0	0	0	1	0	0	0	0	0
ACTR1A	0	0	1	0	0	0	0	0	0	0	0
ADAM7	0	0	0	0	0	0	0	1	0	0	0
ADAMTS19	0	0	0	0	0	0	0	1	0	0	0
ADGRG6	0	0	0	0	0	0	0	0	0	1	0
ADRM1	0	0	0	0	1	1	0	0	0	0	0
AIMP1	0	0	0	0	0	0	0	0	0	1	0
AK1	0	0	0	1	0	0	0	1	0	0	0
AKAP3	0	0	0	1	0	1	0	0	0	0	0
AKAP4	0	0	0	1	0	1	0	0	0	0	1
AKR1B10	0	0	0	1	0	0	0	1	0	0	0
ALB	0	0	1	0	0	0	0	0	0	0	0
ALDOA	0	0	0	1	0	0	0	0	0	1	0
ALMS1	0	0	0	0	0	0	0	0	0	1	0
ANKRD11	0	0	0	0	0	0	0	0	0	1	0
APOA2	1	0	0	0	0	0	0	0	0	0	0
APP	0	0	0	0	0	0	0	0	0	0	1
AQP7	0	0	0	1	0	0	0	0	0	0	1
ART3	0	0	0	0	0	0	0	0	0	1	1
ATG16L1	0	0	0	1	0	0	0	0	0	0	0
ATP5F1A	0	0	0	0	0	0	0	0	0	0	1
ATP5F1B	0	0	0	0	0	0	0	0	0	0	1
ATP6V1A	0	0	0	1	1	1	0	0	0	0	0
ATP6V1B1	0	0	0	1	1	1	0	0	0	0	0
ATP6V1E2	0	0	0	1	1	1	0	0	0	0	0
ATP6V1F	0	0	0	1	1	1	0	0	0	0	0
ATP6V1G1	0	0	0	1	1	1	0	0	0	0	0
ATP6V1H	0	0	0	1	1	1	0	0	0	0	0
BAG6	0	0	0	0	1	0	0	0	0	0	1
CA2	0	0	0	1	0	1	0	0	0	0	1
CABYR	0	0	0	0	0	1	0	0	0	0	0
CALM1	0	0	0	0	0	0	0	0	0	1	0
CALM2	0	0	0	0	0	0	0	0	0	1	0
CAND1	0	0	0	1	0	0	0	0	0	0	0
CAND2	0	0	0	1	0	0	0	0	0	0	0
CAPZA1	0	0	0	0	0	0	0	0	0	0	1
CAPZB	0	0	0	0	0	0	0	0	0	0	1
CCDC113	0	0	0	1	0	0	0	0	0	0	0
CCT3	0	0	0	0	1	0	0	0	0	0	0
CCT6A	0	0	0	0	1	0	0	0	0	0	0
CCT6B	0	0	0	0	0	0	0	0	0	1	0
CCT8	0	0	0	0	0	0	0	0	0	1	0
CD46	1	1	0	0	0	0	0	0	0	0	1
CD59	1	1	0	0	0	0	0	0	0	0	0
CD5L	1	1	0	0	0	0	0	0	0	0	0
CDH1	0	0	0	0	1	0	0	0	0	0	0
CDH2	0	0	0	0	1	0	0	0	0	0	0
CES4A	0	0	0	0	0	0	0	0	1	0	1
CES5A	0	0	0	1	0	1	0	0	1	0	1
CFAP20	0	0	0	1	0	0	0	0	0	0	1
CFAP99	0	0	0	1	0	0	0	0	0	0	1
CKB	0	0	0	0	0	0	0	0	0	0	1
CLTA	0	0	0	1	0	0	0	0	0	0	0
CLU	1	0	0	0	0	0	0	0	1	0	0
CP	1	0	0	0	0	0	0	0	1	1	0
CPPED1	0	0	0	1	0	0	0	0	0	0	1
CRISP1	0	0	0	0	0	1	0	0	1	0	0
CRTAC1	0	0	0	0	0	0	0	0	0	0	1
CSN1S1	0	1	0	0	0	0	1	1	0	0	0
CTSB	0	0	0	1	0	0	0	0	0	0	1
CTSF	0	0	0	0	0	0	0	0	1	0	1
CTSH	0	0	0	0	0	0	0	0	1	0	1
CTSS	0	0	0	0	0	0	0	0	1	0	1
CTSV	0	0	0	0	0	0	0	0	1	0	1
CUL3	0	0	0	0	0	0	0	0	0	1	1
DAZAP1	0	0	0	0	0	0	0	0	0	1	0
DCTN2	0	0	0	0	0	0	0	0	0	1	0
DEFB113	1	0	0	0	0	0	0	0	1	0	0
DEFB115	1	0	0	0	0	0	0	0	1	0	0
DEFB116	1	0	0	0	0	0	0	0	1	0	0
DEFB123	1	0	0	0	0	0	0	0	1	0	1
DEFB129	1	0	0	0	0	0	0	0	1	0	0
DHRS11	0	0	0	0	0	0	0	1	0	0	0
DNAH8	0	0	0	1	0	0	0	0	0	0	0
DNAI1	0	0	0	1	0	0	0	0	0	0	0
DNAI2	0	0	0	1	0	0	0	0	0	0	0
DNAL4	0	0	0	1	0	0	0	0	0	0	0
DNPEP	0	0	0	0	0	0	0	0	1	0	0
DPP4	0	0	0	1	0	0	0	0	0	0	0
DPP7	0	0	0	0	0	0	1	0	0	0	0
ELSPBP1	0	0	0	0	0	0	0	0	0	0	1
ENO1	0	0	0	0	0	0	0	0	0	0	1
ENPP2	0	0	0	0	0	1	0	0	0	0	0
ENPP3	0	0	0	0	0	1	0	0	0	0	0
EQTN	0	0	0	0	0	0	0	1	0	0	0
ERC1	0	0	0	0	0	0	0	0	0	0	1
ERC2	0	0	0	0	0	0	0	0	0	1	0
FAM205C	0	0	0	0	0	0	0	0	0	0	1
FAM71B	0	0	0	0	0	0	0	0	0	0	1
FETUB	0	0	0	0	0	0	0	0	1	0	0
FMR1	0	0	0	0	0	0	0	0	0	1	0
FOLR2	1	0	0	0	0	0	0	0	0	0	1
FSIP2	0	0	0	0	0	0	0	0	0	0	1
GLIPR1L1	0	0	0	0	0	0	0	1	0	0	0
GPX6	0	0	0	0	0	0	0	0	1	0	0
GSN	0	0	0	0	0	0	1	0	0	0	0
HK1	0	0	0	1	0	0	0	1	0	0	0
HK2	0	0	0	1	0	0	0	1	0	0	0
HNRNPA2B1	0	0	0	0	0	0	0	0	0	1	0
HNRNPC	0	0	0	0	0	0	0	0	0	1	0
HNRNPK	0	0	0	0	0	0	0	0	0	1	0
HNRNPM	0	0	0	0	0	0	0	0	0	1	0
HSP90AA1	1	0	0	1	0	0	0	0	0	0	0
HSP90AB1	1	0	0	1	0	0	0	0	0	0	0
HSPA1L	1	0	0	1	0	0	0	0	0	0	1
HSPA2	1	0	0	1	0	0	0	0	0	0	1
HSPA4	1	0	0	1	0	0	0	0	0	0	1
HSPA4L	1	0	0	1	0	0	0	0	0	0	1
HSPA6	1	0	0	1	0	0	0	0	0	0	1
HSPB1	1	0	0	1	0	0	0	0	0	0	0
HYOU1	0	0	0	0	0	0	0	0	1	1	0
IGFBP5	0	0	0	0	0	0	0	0	0	0	1
IL4I1	1	0	0	0	0	1	1	0	0	0	0
IMPA1	0	0	0	1	0	1	1	0	0	0	0
ITIH4	1	1	0	0	0	0	0	0	0	0	0
IZUMO4	0	0	0	0	0	0	0	1	0	0	0
LCN1	0	0	0	0	0	0	0	0	1	0	0
LDHB	0	0	0	0	0	0	0	0	0	0	1
LGALS3BP	0	0	0	0	0	0	0	0	0	0	1
LIPE	0	0	0	0	0	0	0	0	0	1	1
LOC102389470	0	0	0	0	0	0	0	0	1	0	0
LOC102390435	0	1	0	0	0	0	0	0	0	0	1
LOC102390454	1	0	0	0	0	0	0	0	0	0	1
LOC102390798	1	0	0	0	0	0	0	0	0	0	1
LOC102392455	0	0	0	1	0	0	0	0	1	0	0
LOC102393607	0	0	0	0	0	1	0	0	0	0	0
LOC102393680	0	1	0	0	0	0	0	0	0	0	1
LOC102394138	1	0	0	0	0	0	0	0	0	0	0
LOC102394968	0	1	0	0	0	0	0	0	0	0	1
LOC102394973	0	0	0	0	0	0	0	0	1	1	0
LOC102395067	1	0	0	0	0	0	0	0	1	0	0
LOC102395773	0	1	0	0	0	0	0	0	0	0	0
LOC102396583	0	1	0	0	0	0	0	0	0	0	1
LOC102396772	0	0	0	0	0	0	0	0	0	1	0
LOC102397864	0	0	0	0	0	0	0	1	0	0	0
LOC102398195	0	0	0	0	0	0	0	0	0	0	1
LOC102398800	0	0	0	0	0	0	0	0	0	1	0
LOC102399119	0	0	0	0	0	0	0	0	0	1	0
LOC102399593	0	0	0	0	0	0	0	0	0	0	1
LOC102400645	0	0	0	0	0	0	0	0	0	1	0
LOC102400922	0	0	0	0	0	1	1	0	0	0	0
LOC102402381	1	0	0	0	0	0	0	0	0	0	0
LOC102402481	0	1	0	0	0	0	0	0	0	0	1
LOC102402539	0	0	0	1	0	0	0	0	0	0	1
LOC102403094	0	0	0	1	0	0	0	0	0	0	0
LOC102403740	0	0	0	1	0	1	1	0	0	0	0
LOC102405271	0	0	0	0	0	0	0	1	0	0	0
LOC102405698	1	0	0	0	0	0	0	0	1	0	0
LOC102408396	0	0	0	0	0	1	0	0	0	0	0
LOC102408883	0	0	0	0	0	0	0	0	1	0	0
LOC102409057	0	0	0	0	0	0	0	0	0	0	1
LOC102410741	0	0	0	0	0	1	0	0	0	0	0
LOC102410916	0	1	0	0	0	0	0	0	0	0	1
LOC102411025	0	1	0	0	0	0	0	0	0	0	1
LOC102411389	1	0	0	0	0	0	0	0	0	0	0
LOC102411401	0	0	0	0	0	1	0	0	0	0	0
LOC102411950	0	0	0	0	0	0	0	1	0	0	0
LOC102412295	1	0	0	0	0	0	0	0	0	0	0
LOC102413260	1	0	0	0	0	0	0	0	1	0	0
LOC102414740	0	1	0	0	0	0	0	0	0	0	0
LOC112578930	0	0	0	0	0	0	0	0	0	0	1
LOC112581540	0	0	0	1	0	0	0	0	0	0	1
LOC112583793	1	0	0	0	0	0	0	0	0	0	0
LOC112583835	1	0	0	0	0	0	0	0	0	0	0
LOC112587282	0	0	0	0	0	0	0	0	0	0	1
LRCOL1	0	0	0	0	0	0	0	0	0	0	1
LRP2	0	0	0	1	0	0	0	0	0	0	0
LRP8	0	0	0	0	0	0	0	0	1	0	1
LTF	1	0	0	0	0	0	0	0	0	0	0
LUZP2	1	1	0	0	0	0	0	0	0	0	0
LYPD4	0	0	0	0	0	0	0	1	0	0	1
MDH1	0	0	0	0	0	0	0	0	0	0	1
MDK	0	0	0	0	0	0	0	0	0	1	0
MIF	0	1	0	0	0	0	0	1	0	0	0
MPST	1	0	0	0	0	0	0	0	1	1	0
MSMB	1	0	0	1	0	0	0	0	0	0	0
MYL6	0	0	0	0	0	0	0	0	0	1	0
MYO5A	0	0	0	1	0	0	0	0	0	0	0
NCOA3	0	0	0	0	0	0	0	0	0	0	1
NDRG3	0	0	0	0	0	0	0	0	0	1	0
NECTIN2	0	0	0	0	0	0	0	0	0	1	0
NME8	0	0	0	1	0	0	0	0	0	1	0
NPPC	0	0	0	1	0	0	1	0	0	0	1
NSFL1C	0	0	0	0	0	1	0	1	0	0	0
ODF2	0	0	0	1	0	0	0	0	0	0	0
ODF3	1	0	0	1	0	0	0	0	0	0	0
ODF3B	1	0	0	1	0	0	0	0	0	0	0
PAM	0	0	0	1	0	0	0	0	0	0	0
PARK7	0	0	0	0	0	0	0	1	0	0	0
PCBP2	1	0	0	0	0	0	0	0	0	0	0
PDGFA	0	0	0	0	0	0	0	0	0	1	0
PDGFD	0	0	0	0	0	0	0	0	0	1	0
PDIA3	0	0	0	0	1	0	0	0	0	0	0
PDIA6	0	0	0	0	1	0	0	0	0	0	0
PEBP1	0	0	0	0	0	0	0	0	1	0	0
PEBP4	0	0	0	1	0	0	0	0	0	0	1
PFDN1	0	0	0	0	0	0	0	0	0	1	1
PFDN2	0	0	0	0	0	0	0	0	0	1	1
PFDN5	0	0	0	0	0	0	0	0	0	1	1
PFDN6	0	0	0	0	0	0	0	0	0	1	1
PLA2G7	0	0	0	1	0	1	0	0	0	0	0
PLIN3	0	0	0	0	0	0	0	0	1	1	1
PPIA	1	0	0	0	0	0	0	0	1	0	0
PPIB	1	0	0	0	0	0	0	0	1	0	0
PPME1	0	0	0	1	0	0	0	0	0	0	0
PPP1R7	0	0	0	1	0	0	0	0	1	0	0
PPP4R1	0	0	0	0	0	0	0	0	0	1	0
PRDX1	1	0	0	0	0	0	0	0	0	0	0
PRDX4	1	0	0	0	0	0	0	0	0	0	0
PRKACA	0	0	0	0	0	1	0	0	0	0	1
PRKAR1A	0	0	0	0	0	1	0	0	0	0	0
PRKAR2A	0	0	0	0	0	1	0	0	0	0	0
PRKAR2B	0	0	0	0	0	1	0	0	0	0	0
PRKCSH	0	0	0	0	0	0	0	0	1	0	0
PROCA1	0	0	0	1	0	0	0	0	0	0	1
PROM1	0	0	0	0	0	1	0	0	0	1	0
PROM2	0	0	0	0	0	1	0	0	0	1	0
PSAP	0	0	0	0	0	0	0	1	0	0	0
PSMA1	1	0	0	0	0	0	0	0	0	0	1
PSMA2	1	0	0	0	0	0	0	0	0	0	1
PSMA4	1	0	0	0	0	0	0	0	0	0	1
PSMA5	1	0	0	0	0	0	0	0	0	0	1
PSMA6	1	0	0	0	0	0	0	0	0	0	1
PSMA8	1	0	0	0	0	0	0	0	0	0	1
PSMB6	0	0	0	0	1	0	0	0	0	0	0
PSMC2	0	0	0	0	0	1	0	0	0	0	0
PSMC3	0	0	0	0	0	1	0	0	0	0	0
PSMC6	0	0	0	0	0	1	0	0	0	0	0
PSMD2	0	0	0	0	1	0	0	0	0	0	0
PSMD4	0	0	0	0	1	0	0	0	0	0	0
PSMD7	0	0	0	0	1	0	0	0	0	0	0
QSOX1	0	0	0	0	0	0	0	0	0	0	1
RAB10	0	0	0	0	0	0	0	0	1	0	0
RAB11A	0	0	0	0	0	0	0	0	1	0	0
RAB11B	0	0	0	0	0	0	0	0	1	0	0
RAB1A	0	0	0	0	0	0	0	0	1	0	0
SEMA3F	0	0	0	0	0	0	0	0	1	0	0
SERPINA1	0	0	0	0	0	0	0	0	1	0	0
SERPINC1	0	0	0	0	0	0	0	0	1	0	0
SERPINF2	0	0	0	0	0	0	0	0	1	0	0
SIAE	0	0	0	0	0	0	0	0	0	1	0
SIRPA	0	0	0	1	0	0	0	0	0	0	0
SLC38A10	0	0	1	0	0	0	0	0	0	0	0
SOD1	0	0	1	0	0	0	0	0	1	0	0
SOD3	0	0	1	0	0	0	0	0	1	0	0
SORD	0	0	0	0	0	0	0	1	0	0	0
SORT1	1	0	0	0	0	0	0	0	0	0	0
SPA17	0	0	0	0	1	0	0	0	0	0	0
SPA3	0	0	0	1	0	0	0	0	0	0	0
SPATA18	0	0	0	0	0	0	0	0	0	1	1
SPATA3	0	0	0	0	0	0	0	0	0	1	1
SPERT	0	0	0	0	0	0	0	0	0	1	0
SPESP1	0	0	0	0	0	0	0	1	0	0	0
SPINK5	0	0	0	0	0	1	0	0	0	0	1
SPINK8	0	0	0	0	0	0	0	0	1	0	0
SPP1	0	0	0	0	0	0	0	0	0	0	1
SRPK2	0	0	0	0	0	0	0	0	0	1	0
SSH2	0	0	0	0	0	1	0	0	0	0	0
ST6GAL1	0	0	0	0	0	0	0	0	1	0	0
STAU1	0	0	0	0	0	0	0	0	0	1	1
STAU2	0	0	0	0	0	0	0	0	0	1	1
TEX101	0	0	0	0	0	0	0	0	0	0	1
THEG	0	0	0	0	0	0	0	0	0	1	0
THEGL	0	0	0	0	0	0	0	0	0	1	0
TIMP2	0	0	0	0	0	0	0	0	0	0	1
TMPRSS11A	0	0	0	1	0	0	0	0	0	0	1
TPP1	0	0	0	0	0	1	0	0	0	0	0
TPP2	0	0	0	0	0	1	0	0	0	0	0
TPPP2	0	0	0	1	0	0	0	0	0	1	1
TSSK1B	0	0	0	0	0	0	0	0	0	1	0
TUBA4A	0	0	0	1	0	0	0	0	0	0	0
TUBA8	0	0	0	1	0	0	0	0	0	0	0
TUBB4B	0	0	0	0	0	0	0	0	0	0	1
TUBB6	0	0	0	0	0	0	0	0	0	0	1
TUT7	0	0	0	0	0	0	0	0	0	1	0
UBQLN1	0	0	0	0	0	0	0	0	0	1	0
UBXN11	0	0	0	0	0	1	0	0	0	0	0
UGP2	0	0	0	0	0	0	0	1	0	0	0
VAMP1	0	0	0	0	0	0	1	0	0	0	0
VAMP2	0	0	0	0	0	0	0	0	1	0	0
VAMP3	0	0	0	0	0	0	0	0	1	0	0
VCL	0	0	0	0	0	1	1	0	0	0	0
VCP	0	0	0	0	0	0	0	0	0	0	1
WFDC13	0	0	0	0	0	0	0	0	1	0	0
WFDC2	0	0	0	0	0	0	0	0	1	0	0
YBX1	0	0	0	0	0	0	0	0	0	1	0
YWHAE	0	0	0	1	0	0	0	0	0	1	1
YWHAH	0	0	0	0	0	0	0	0	0	1	1
ZPBP	0	0	0	0	0	0	0	1	0	0	0

**Comment by databio2022** [comment]
log2FC column is missing.

**Comment by vipulbatra1985** [comment]
The website says it's optional. I will add it though

**Comment by vipulbatra1985** [comment]
Still doesn't work. 
[DEMO.csv](https://github.com/databio2022/GraphBio/files/9686780/DEMO.csv)

**Comment by vipulbatra1985** [comment]
It is so frustrating. Sorry, this one. 
[DEMO.csv](https://github.com/databio2022/GraphBio/files/9686807/DEMO.csv)

**Comment by databio2022** [comment]
Hi,
Yes, log2FC column is not required. I checked your file and found your file contain 11 pathways or biological processes which over maximum 8 colors allowed by default "color1" setting. In this case, you can select "color2" in right parameter settings panel after upload file irrespective of error information, it will work. This is result for your data. 
![image](https://user-images.githubusercontent.com/101156176/193373276-03c18729-68c0-40ae-9095-e9fdd51aed46.png)
