### ISSUE TITLE
Error when uploading datasets for certain visualization tools

### ISSUE THREAD

**Issue by kmgwilliam** [databio2022/GraphBio#5]
Hello. I have formatted my RNA-seq data to those of the example on the GraphBio cite but unforutnatley keep getting the erro in the image below. Do you have any issue why this may be? I have even titled the columns with the exact names/capitalization as your examples. Thank you for any help!

![GraphBio](https://user-images.githubusercontent.com/110115401/195695343-e4169c0c-f3eb-45f4-ad05-a6945665fa51.png)

**Comment by databio2022** [comment]
Hi,
Please check if first column is duplicated and any filter has been applied for the file. Volcano plot data should not be filtered based on statistical signifcance, it also should contain other non-significant data.

**Comment by kmgwilliam** [comment]
Hello,

Thank you so much. I believe that the dataset I was given only includes
data that is statistically significant so I will try again with a different
dataset.

Thank you!
Katie
