### ISSUE TITLE
Heatmap Error

### ISSUE THREAD

**Issue by ayal11** [databio2022/GraphBio#6]
Hi, I'm trying to create a gene expression heatmap and I keep getting an error when I add a metadata file. I can't figure out why. I've formatted the data as in your example. Please check. Thank you. 

[Heatmap Data.csv](https://github.com/databio2022/GraphBio/files/9792343/Heatmap.Data.csv)
[Heatmap metadata.csv](https://github.com/databio2022/GraphBio/files/9792344/Heatmap.metadata.csv)

**Comment by databio2022** [comment]
Hi,
For metadata file header, please use "sample" and "group".

**Comment by ayal11** [comment]
Oh that was a quick fix. Works now. Thanks.
